--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisuke/GameRuleToggler
build-by-default: true
branches:
- main
projects:
  GameRuleToggler:
    path: ""
    libs:
      - src: DaisukeDaisuke/AwaitFormOptions/AwaitFormOptions
        version: 3.0.2
      - src: Cosmoverse/AwaitForm/AwaitForm
        varsion: 0.0.3
      - src: SOF3/await-generator/await-generator
        varsion: 3.6.1
...
